### ISSUE TITLE
Tracker SDKs: docs update

### ISSUE THREAD

**Issue by sdirosa** [objectiv/objectiv.io#514]
We are due for a big documentation update.

- [x] react, react-native, LocationContextWrapper docs are incorrect: missing href from props, also in the examples
- [x] react, react-native, useOnToggle/useTrackOnToggle in combination with isContextEqual
- [x] react, react-native, useOnContextChange
- [x] react, react-native, remove useOnChange
- [x] react, react-native, remove useTrackOnChange
- [x] react, react-native, update useOnToggle
- [x] react, react-native, update useTrackOnToggle
- [x] react, react-native, hooks examples with enriching of location context or global context
- [x] react native: identitycontext examples
